name: Bug report
description: Create a report to help us improve
title: "[BUG] "
labels: 
  - bug
body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.

  - type: textarea
    id: reproduce
    attributes:
      label: "To Reproduce"
      description: "Steps to reproduce the behavior"
      placeholder: "1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See error"

  - type: input
    id: expected
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happen"

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem"
      placeholder: "Upload screenshots here if applicable"

  - type: input
    id: version
    attributes:
      label: "Version"
      description: "Version of the bot or application where the bug occurred (e.g. 1.0.0)"

  - type: input
    id: operating-system
    attributes:
      label: "Operating System"
      description: "The operating system you are using (e.g., Windows 10, macOS Catalina, Ubuntu 20.04)"

  - type: input
    id: node-version
    attributes:
      label: "Node.js Version"
      description: "The version of Node.js you are using (e.g., 16.13.0)"

  - type: input
    id: discord-version
    attributes:
      label: "Discord.js Version"
      description: "The version of Discord.js you are using (if applicable, e.g., 14.3.0)"

  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "Paste any relevant logs or error messages here"
      placeholder: "Include any logs or error messages here if available"

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context about the problem here, such as configuration details, related issues, or steps that led to the bug"
